#!/bin/bash

# One of the following: xrandr, xbacklight, kernel
METHOD="light"

# Left click
if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  light -A 5
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  light -U 5
fi

URGENT_VALUE=10
curBrightness=$(light -G)

if [[ "${curBrightness}" -lt 0 ]]; then
  exit
fi

percent=$(echo "scale=0;${curBrightness}" | bc -l)

percent=${percent%.*}

if [[ "${percent}" -lt 0 ]]; then
  exit
fi

echo "${percent}%"
echo "${percent}%"
echo ""

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi